version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fiu-user
      - MONGO_INITDB_ROOT_PASSWORD=fiu-password
      - MONGO_INITDB_DATABASE=fiu-db
    command: mongod --auth

  solr:
    image: solr:8.8
    container_name: solr-dev
    environment:
      - SOLR_USER=fiu-solr-usr
      - SOLR_PASSWORD=fiu-solr-password
    ports:
      - "8983:8983"
    volumes:
      - ./indexed-data:/var/solr/data

volumes:
  mongodb_data: